//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRDB.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

public class SRDB {
    public SRSearch mDB;
    private SRTag mTag;

    public void open(String dbName) {

    }

    public void close() {

    }

    public void insertInfo(String voiceFilePath, String docFilePath) {

    }

    public void deleteInfo(String voiceFilePath) {

    }

    public void updateInfo(String voiceFilePath, String docFilePath) {

    }

    public void insertTag(String voiceFilePath, SRTagItem tagItem) {

    }

    public void deleteTag(String voiceFilePath, SRTagItem tagItem) {

    }

    public void updateTag(String voiceFilePath, SRTagItem tagItem) {

    }

    public void selectAll() {

    }

    public void selectByText(String text) {

    }

    public void selectByText(String voiceFileName, String text) {

    }
}
