//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRDoc.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

public class SRDoc {
    private Object mFile;
    private Object mPageNum;

    public void open(String filePath) {

    }

    public void destroy() {

    }

    public void gotoPage(int page) {

    }

    public void drawPage() {

    }

    public void getPageNum() {

    }

    public void getTotalPageNum() {

    }
}
