//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRPlayView.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

import android.content.Context;
import android.util.AttributeSet;

public class SRPlayView extends SRVoiceView {

    public SRPlayView(Context context) {
        super(context);
    }
    
    public SRPlayView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
}
