//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRRecordView.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

import android.content.Context;
import android.util.AttributeSet;

public class SRRecordView extends SRVoiceView {

    public SRRecordView(Context context) {
        super(context);
    }
    public SRRecordView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
}
