//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRSearchView.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

import java.util.ArrayList;
import java.util.List;
import android.content.Context;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.widget.ArrayAdapter;
import android.widget.FrameLayout;
import android.widget.ListView;

public class SRSearchView extends FrameLayout {
    private Context mContext;
    private SRSearchControllerInterface mController;
    ListView mListView;
    private ArrayAdapter<String> mAdapter;
    
    //{{TESTCODE
    private String[] mStrings = Cheeses.sCheeseStrings;
    //}}TESTCODE

    public SRSearchView(Context context) {
        super(context);
        initView(context);
    }
    
    
    public SRSearchView(Context context, SRSearchControllerInterface controller) {
        super(context);
        mController = controller;
        initView(context);
    }
    
    public SRSearchView(Context context, AttributeSet attrs) {
        super(context, attrs);
        initView(context);
    }

    private void initView(Context context) {
        mContext = context;
        LayoutInflater inflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        inflater.inflate(R.layout.sr_searchview_layout, this, true);
          
        SRDataSource datasource = new SRDataSource(mContext);
        datasource.open();

        ArrayList<SRTagDb> tags = datasource.getAllTag();

        datasource.close();
        SRDebugUtil.SRLog("tags = "+tags);
        
        mListView = (ListView)findViewById(R.id.SRSearchListView);
        
        SRTagListAdapter tagListAdapter = new SRTagListAdapter(mContext, R.layout.sr_tag_list, tags);

        mListView.setAdapter(tagListAdapter);

        mListView.setTextFilterEnabled(true);
    }
    
    public void clearTextFilter() {
        if (mListView != null) {
            mListView.clearTextFilter();
        }
    }
    
    public void setFilterText(String filterText) {
        if (mListView != null) {
            mListView.setFilterText(filterText);
        }        
    }
    
    
}


