//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRSearch.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

import android.database.Cursor;

public class SRSearch {
    public void getAllTagList() {

    }

    /**
     * DB에 있는 Tag text 데이터를 검색
     * 
     * @param text
     **/
    public void search(String text) {

    }
}
