//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRShare.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

/**
 * DropBox API ÀÌ¿כ
 **/
public class SRShare {
    public void authentication() {

    }

    public void putFile(String filePath) {

    }
}
