//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRTagItemPage.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

public class SRTagItemPage implements SRTagItemData {
    private Integer mPage;

    public Object get() {
        return mPage;
    }

    public void set(Object data) {
        mPage = (Integer)data;
    }
}
