//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRTag.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

public class SRTag {
    private SRTagItem mTagItems;

    /**
     * DB에도 동시에 저장한다.
     * 
     * @param tagItem
     **/
    public void insert(SRTagItem tagItem) {

    }

    /**
     * DB에도 동시에 저장한다.
     * 
     * @param tagItem
     **/
    public void delete(SRTagItem tagItem) {

    }

    /**
     * DB에도 동시에 저장한다.
     * 
     * @param tagItem
     **/
    public void update(SRTagItem tagItem) {

    }

    public void getTagItem(int position) {

    }

    public void getAllTagItem() {

    }
}
