//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRTagItemPhoto.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

public class SRTagItemPhoto implements SRTagItemData {
    private String mPhoto;

    public Object get() {
        return mPhoto;
    }

    public void set(Object data) {
        mPhoto = (String)data;
    }
}
