//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRTagItem.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

import java.util.Date;

public class SRTagItem {
    private Date mDate;
    private int mPosition;
    private SRTagItemData mTagData;

    public SRTagItem(int position, SRTagItemData tagData) {
        super();
        mDate = new Date();
        this.mPosition = position;
        this.mTagData = tagData;
    }

    public Date getDate() {
        return mDate;
    }

    public void setPosition(int position) {
        mPosition = position;
    }

    public int getPosition() {
        return mPosition;
    }

    public void setTagData(SRTagItemData tagData) {
        mTagData = tagData;
    }

    public SRTagItemData getTagData() {
        return mTagData;
    }
}
