//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRTagItem.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

import java.util.Date;

public class SRTagItem {
    private Date mDate;
    private int mPosition;
    private SRTagItemData mTagData;

    public void create(int position) {

    }

    public void getDate() {

    }

    public void setPosition(int position) {

    }

    public void getPosition() {

    }

    public void setTagData(SRTagItemData tagData) {

    }

    public void getTagData() {

    }
}
