//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRTagItemText.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

public class SRTagItemText implements SRTagItemData {
    private String mText;

    public Object get() {
        return mText;
    }

    public void set(Object data) {
        mText = (String)data;
    }
}
