//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRVoice.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

public class SRVoice {
    private SRTag mTag;
    private SRDoc mDoc;
    public SRDB mDB;
    public SRShare mShare;

    /**
     * 음성녹음 파일과 Tag DB 읽는다
     * 
     * Tag DB는 음성녹음 파일 이름을 Key로 가진다
     * 
     * @param filePath
     **/
    public void open(String filePath) {

    }

    public void getDoc() {

    }

    public void setDoc(SRDoc doc) {

    }

    public void recordStart() {

    }

    public void recordStop() {

    }

    public void save() {

    }

    public void play() {

    }

    public void seekTo(int position) {

    }

    public void playPause() {

    }

    public void playStop() {

    }

    public void getCurrentPosition() {

    }

    public void getDuration() {

    }

    public void saveBasicInfo(Object voiceFilePath, Object docFilePath) {

    }

    public void share() {

    }
}
