
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRVoiceView.java
//  @ Date : 2013-05-30
//  @ Author : 
//
//
package com.unus.smartrecorder;

import java.util.List;

import android.app.AlertDialog;
import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.database.Cursor;
import android.graphics.drawable.BitmapDrawable;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;

public class SRVoiceView extends RelativeLayout{
    public static final int DIALOG_INPUT_BASIC_INFO = 1; // Input Basic Info Dialog
    public static final int DIALOG_INPUT_TEXT_TAG = 2; // Input Text Tag Dialog

    private Context mContext;
	private Button mBtnRecorder, mBtnStop, mBtnPlay;
    private ListView mTagListView;
    private ArrayAdapter<String> mTagListViewAdapter;
    private ImageButton mTextTagBtn, mPhotoTagBtn, mRecordBtn, mStopBtn;
    SRVoice mSRVoice;
    private SRVoiceViewListner mSRVoiceViewListner;
    
    private EditText mTitleView;    // Basic Info Dialog
    private TextView mDocPathView;  // Basic Info Dialog
    private String mTitle;         // Basic Info Dialog
    private String mDocPath;        // Basic Info Dialog
    
    //{{TESTCODE
    private String[] mStrings = Cheeses.sCheeseStrings;
    //}}TESTCODE

    
    public SRVoiceView(Context context) {
        super(context);
        initView(context);
    }
    
    public SRVoiceView(Context context, AttributeSet attrs) {
        super(context, attrs);
        initView(context);
    }
    
    private void initView(Context context) {
        mContext = context;
        LayoutInflater inflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            inflater.inflate(R.layout.sr_voiceview_layout, this, true);

            
            
            SRDataSource datasource = new SRDataSource(mContext);
            datasource.open();
//          
            datasource.createVoice("testVoicePath", "testDocPath");
////            
//            datasource.createTag(2, 1, "good2", "00:01");
//            
//            List<SRVoiceModel> voices = datasource.getAllVoice();
//            
            List<SRTagModel> tags = datasource.getTagByVoiceId((long) 2);
//            SRDebugUtil.SRLog("voices = "+voices);
//            SRDebugUtil.SRLog("tags = "+tags);
            
            
            mSRVoice = new SRVoice();
            
            
            
            mBtnRecorder = (Button) findViewById(R.id.btnRecorder);
            mBtnRecorder.setOnClickListener(new OnClickListener() {
                
                @Override
                public void onClick(View v) {
                    // TODO Auto-generated method stub
                    //DebugUtil.SRLog("onClick()");
                	mSRVoice.recordStart(mContext);
                }
            });
            
            mBtnStop = (Button) findViewById(R.id.btnStop);
            mBtnStop.setOnClickListener(new OnClickListener(){
            	@Override
            	public void onClick(View v) {
            		// TODO Auto-generated method stub
            		mSRVoice.recordStop(mContext);
            	}
            });
            
            
            mBtnPlay = (Button) findViewById(R.id.btnPlay);
            mBtnPlay.setOnClickListener(new OnClickListener(){
            	@Override
            	public void onClick(View v) {
            		// TODO Auto-generated method stub
            		mSRVoice.play();
            	}
            });
            mTagListView = (ListView) findViewById(R.id.tagListView);
            mTagListView.setAdapter(mTagListViewAdapter = new ArrayAdapter<String>(

            mContext, android.R.layout.simple_list_item_1, Cheeses.sCheeseStrings));

            
            
            mTextTagBtn = (ImageButton) findViewById(R.id.textTagBtn);
            mTextTagBtn.setOnClickListener(new OnClickListener(){
                @Override
                public void onClick(View v) {

                }
            });
            
            mPhotoTagBtn = (ImageButton) findViewById(R.id.photoTagBtn);
            mPhotoTagBtn.setOnClickListener(new OnClickListener(){
                @Override
                public void onClick(View v) {

                }
            });
            
            mRecordBtn = (ImageButton) findViewById(R.id.recordBtn);
            mRecordBtn.setOnClickListener(new OnClickListener(){
                @Override
                public void onClick(View v) {
                    SRDebugUtil.SRLog("Record Click");
                    if (mSRVoiceViewListner != null)
                    	//SRDebugUtil.SRLog("good");
                        mSRVoiceViewListner.showInputBasicInfo();
                }
            });
            
            mStopBtn = (ImageButton) findViewById(R.id.stopBtn);
            mStopBtn.setOnClickListener(new OnClickListener(){
                @Override
                public void onClick(View v) {

                }
            });
    }
    
    public void setSRVoiceViewListner(SRVoiceViewListner listner) {
        mSRVoiceViewListner = listner;
    }
    
    public void setDocPath(String path) {
        mDocPath = path;
        if (mDocPathView != null)
            mDocPathView.setText(mDocPath);
    }
    
    public Dialog createDialog(Context context, int id) {
        LayoutInflater factory = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        switch(id) {
        case DIALOG_INPUT_BASIC_INFO:
            final View inputBasicInfoView = factory.inflate(
                    R.layout.sr_input_basic_info_dialog, null);
            mTitleView = (EditText)inputBasicInfoView.findViewById(R.id.titleText);
            mDocPathView = (TextView)inputBasicInfoView.findViewById(R.id.docPathText);
            mDocPathView.setSelected(true);
            final ImageButton explorerBtn = (ImageButton)inputBasicInfoView.findViewById(R.id.explorerBtn);
            explorerBtn.setOnClickListener(new OnClickListener() {
                
                @Override
                public void onClick(View v) {
                    if (mSRVoiceViewListner != null) 
                        mSRVoiceViewListner.showFileExplorer();
                }
            });
            
            return new AlertDialog.Builder(context)
                    .setTitle(R.string.input_basic_info)
                    .setView(inputBasicInfoView)
                    .setPositiveButton(android.R.string.ok,
                            new DialogInterface.OnClickListener() {
                                public void onClick(DialogInterface dialog,
                                        int whichButton) {
                                    mTitle = mTitleView.getText().toString();
                                    
                                    SRDebugUtil.SRLog("Input Basic Info : Title : " + mTitle + " Doc : " + mDocPath);
                                }
                            })
                    .setNegativeButton(android.R.string.cancel,
                            new DialogInterface.OnClickListener() {
                                public void onClick(DialogInterface dialog,
                                        int whichButton) {
                                    mTitle = "";
                                    mDocPath = "";
                                }
                            }).create();
            
        case DIALOG_INPUT_TEXT_TAG:
            final View inputTextTagView = factory.inflate(
                    R.layout.sr_input_basic_info_dialog, null);
            return new AlertDialog.Builder(context)
                    .setTitle(R.string.input_basic_info)
                    .setView(inputTextTagView)
                    .setPositiveButton(android.R.string.ok,
                            new DialogInterface.OnClickListener() {
                                public void onClick(DialogInterface dialog,
                                        int whichButton) {

                                    /* User clicked OK so do some stuff */
                                }
                            })
                    .setNegativeButton(android.R.string.cancel,
                            new DialogInterface.OnClickListener() {
                                public void onClick(DialogInterface dialog,
                                        int whichButton) {

                                    /* User clicked cancel so do some stuff */
                                }
                            }).create();
        default:
            return null;
        }
    }
}
